In [2]:
import numpy as np

In [4]:
oneDim = np.array([1.0, 2, 3, 4, 5])
print(oneDim)
print("#Dimensions =", oneDim.ndim)
print("Dimension =", oneDim.shape)
print("Size =", oneDim.size)
print("Array type =", oneDim.dtype)

[1. 2. 3. 4. 5.]
#Dimensions = 1
Dimension = (5,)
Size = 5
Array type = float64


In [5]:
twoDim = np.array([[1,2],[3,4],[5,6],[7,8]]) # a two-dimensional array (matrix) print(twoDim)
print("#Dimensions =", twoDim.ndim)
print("Dimension =", twoDim.shape)
print("Size =", twoDim.size)
print("Array type =", twoDim.dtype)

#Dimensions = 2
Dimension = (4, 2)
Size = 8
Array type = int64


In [6]:
arrFromTuple = np.array([(1,'a',3.0),(2,'b',3.5)]) # create ndarray from tuple print(arrFromTuple)
print("#Dimensions =", arrFromTuple.ndim)
print("Dimension =", arrFromTuple.shape)
print("Size =", arrFromTuple.size)
print("Array type =", arrFromTuple.dtype)

#Dimensions = 2
Dimension = (2, 3)
Size = 6
Array type = <U32


In [7]:
print(np.array([1]).shape)
print(np.array([1,2]).shape)
print(np.array([[1],[2]]).shape)
print(np.array([[[1,2,3],[1,2,3]]]).shape)
print(np.array([[[[]]]]).shape)

(1,)
(2,)
(2, 1)
(1, 2, 3)
(1, 1, 1, 0)


In [9]:
print(np.arange(-10, 10,2))
print(np.arange(12).reshape(3,4))
print(np.arange(12).reshape(3,4).shape)
print(np.linspace(0, 1, 10))
print(np.logspace(-3,3,7))

[-10  -8  -6  -4  -2   0   2   4   6   8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [10]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([[1], [2], [3]])
print(x+y)

[[ 3  5  7  9 11]
 [ 4  6  8 10 12]
 [ 5  7  9 11 13]]


In [17]:
x = np.arange(-5, 5)
print(x)

y = x[3:5]
print(y)
y[:] = 10000
print(x)
print(y)
z = x[3:5].copy()
print(z)
z[:] = 2000
print(z)
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[-2 -1]
[   -5    -4    -3 10000 10000     0     1     2     3     4]
[10000 10000]
[10000 10000]
[2000 2000]
[   -5    -4    -3 10000 10000     0     1     2     3     4]


In [23]:
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # a 2-dim list print(my2dlist)
print(my2dlist[2]) 
print(my2dlist[:][2]) 

my2darr = np.array(my2dlist) 
print(my2darr)
# print(my2darr[2][:])
print(my2darr[2,:])
print(my2darr[1,:2])
# print(my2darr[:][2])
print(my2darr[:,2])
print(my2darr[:,-1])
print(my2darr[:2,2:])
print(my2darr[::2,2:])

[9, 10, 11, 12]
[9, 10, 11, 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[5 6]
[ 3  7 11]
[ 4  8 12]
[[3 4]
 [7 8]]
[[ 3  4]
 [11 12]]


In [24]:
my2darr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
print(my2darr)
# a 2-dim list
print()
sliced = my2darr[::2,2:] 
print(sliced) 
print(type(sliced))
print() 
sliced[:,:] = 1000 
print(my2darr)
print() 
sliced[0,0] = 2000 
print(my2darr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 3  4]
 [11 12]]
<class 'numpy.ndarray'>

[[   1    2 1000 1000]
 [   5    6    7    8]
 [   9   10 1000 1000]]

[[   1    2 2000 1000]
 [   5    6    7    8]
 [   9   10 1000 1000]]


In [25]:
# slicing vs masking vs integer array indexing
x = np.array([1,2,3]) 
print(x[1:]) 
print(x[1:][0])
print()
print(x[[True, False, True]])
print()
print(x[[2,1]])
print(x[[2,1,1,1,0]])
print() 
x[[2,1,1,1,0]] = 0 
print(x)

[2 3]
2

[1 3]

[3 2]
[3 2 2 2 1]

[0 0 0]


In [27]:
y = np.arange(35).reshape(5,7) 
print(y)
b = y > 20
print(b)
print() 
t = y[b] 
print(t)
# Filtering result is always one-dimensional; it's a copy; not indexing
print() 
t[:3] = 1000 
print(t) 
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]

[21 22 23 24 25 26 27 28 29 30 31 32 33 34]

[1000 1000 1000   24   25   26   27   28   29   30   31   32   33   34]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [33]:
M = np.arange(35).reshape(5,7)
M

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [30]:
M[M%2 == 0] = 0
M

array([[ 0,  1,  0,  3,  0,  5,  0],
       [ 7,  0,  9,  0, 11,  0, 13],
       [ 0, 15,  0, 17,  0, 19,  0],
       [21,  0, 23,  0, 25,  0, 27],
       [ 0, 29,  0, 31,  0, 33,  0]])

In [32]:
M = np.arange(35).reshape(5,7)
M[M%2 == 0] = -M[M%2 == 0]
M

array([[  0,   1,  -2,   3,  -4,   5,  -6],
       [  7,  -8,   9, -10,  11, -12,  13],
       [-14,  15, -16,  17, -18,  19, -20],
       [ 21, -22,  23, -24,  25, -26,  27],
       [-28,  29, -30,  31, -32,  33, -34]])

In [35]:
np.where(M % 2 == 0, M, -M)

array([[  0,  -1,   2,  -3,   4,  -5,   6],
       [ -7,   8,  -9,  10, -11,  12, -13],
       [ 14, -15,  16, -17,  18, -19,  20],
       [-21,  22, -23,  24, -25,  26, -27],
       [ 28, -29,  30, -31,  32, -33,  34]])

In [36]:
np.where(M % 2 == 0, M, 0)

array([[ 0,  0,  2,  0,  4,  0,  6],
       [ 0,  8,  0, 10,  0, 12,  0],
       [14,  0, 16,  0, 18,  0, 20],
       [ 0, 22,  0, 24,  0, 26,  0],
       [28,  0, 30,  0, 32,  0, 34]])

In [41]:
my2darr = np.arange(1, 13, 1).reshape(4,3)
print(my2darr)

indices = [2, 1, 0, 3]
print(my2darr[indices,:2])

rowIndex = [0,0,1,2,3] # row index into my2darr 
columnIndex = [0,2,0,1,2] # column index into my2darr 
print(my2darr[rowIndex,columnIndex]) # element-wise

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 7  8]
 [ 4  5]
 [ 1  2]
 [10 11]]
[ 1  3  4  8 12]


In [42]:
M = np.arange(25).reshape(5,5) 
print(M)
print(M[M%2==1]) 
print(np.argwhere(M >= 20)) 
print(np.where(M % 2 == 1, M, 0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]
[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]


In [44]:
t = np.array([1, 2, 3])
print(t.shape)
x = t[:, np.newaxis]
print(x.shape)
y = t[np.newaxis,:]
print(y.shape)
print(x)
print(y)

(3,)
(3, 1)
(1, 3)
[[1]
 [2]
 [3]]
[[1 2 3]]


In [48]:
t = np.array([[1, 2, 3], [4, 5, 6]])
print(t.shape)
print(t[:,:,np.newaxis].shape)
print(t[:,:,np.newaxis])
print()

print(t[np.newaxis,:, :].shape)
print(t[np.newaxis,:, :])
print()

print(t[:, np.newaxis, :].shape)
print(t[:, np.newaxis, :])

(2, 3)
(2, 3, 1)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]

(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]

(2, 1, 3)
[[[1 2 3]]

 [[4 5 6]]]


In [49]:
np.array([[1,2],[3,4]]) + np.array([[10]])

array([[11, 12],
       [13, 14]])

In [50]:
A = np.array([1, 2])
B = np.array([[10],[100]])
print(A.shape, B.shape)
C = A + B
C

(2,) (2, 1)


array([[ 11,  12],
       [101, 102]])

In [53]:
X = np.array([[1]]*3)
Y = np.array([[0]*10])
print(X.shape)
print(Y.shape)
Z = X + Y
print(Z)

(3, 1)
(1, 10)
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [57]:
X = np.array([[1]]*3)
print(X)
X = X[ np.newaxis,:,:]
print(X)
Y = np.array([[0]*10])
print(X.shape)
print(Y.shape)
Z = X + Y
print(Z)

[[1]
 [1]
 [1]]
[[[1]
  [1]
  [1]]]
(1, 3, 1)
(1, 10)
[[[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]]


In [58]:
a = np.array([[1],[2],[3]])
b= a.T
a+b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [60]:
v = np.array([10, 20, 30])
w = np.array([5, 6])
X, Y = np.meshgrid(v,w)
print(X)
print(Y)
X + Y

[[10 20 30]
 [10 20 30]]
[[5 5 5]
 [6 6 6]]


array([[15, 25, 35],
       [16, 26, 36]])

In [73]:
X = np.array([[0,0,0], [1,1,1]])
X.shape

(2, 3)

In [74]:
X.sum(axis=0)

array([1, 1, 1])

In [75]:
X.sum(axis=1)

array([0, 3])

In [81]:
X = np.array(range(1, 24+1)).reshape(2,3,4)
print(X)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [77]:
X.shape

(2, 3, 4)

In [78]:
X.sum(axis=0)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [79]:
X.sum(axis=1)

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [80]:
X.sum(axis=2)

array([[10, 26, 42],
       [58, 74, 90]])

In [83]:
X.sum(axis=(1,2))

array([ 78, 222])

In [89]:
print(X.sum(axis=(0,1,2)))
print(X.sum(axis=(1,2,0)))
print(X.sum(axis=(2,1,0)))
print(X.sum(axis=(2,0,1)))

300
300
300
300


In [92]:
X = np.array(np.arange(2*3, 0, -1).reshape(2,3))
print(X)
print()
print(np.sort(X, axis = 0))
print()
print(np.sort(X, axis = -1))
print()
print(np.sort(X, axis = None))

[[6 5 4]
 [3 2 1]]

[[3 2 1]
 [6 5 4]]

[[4 5 6]
 [1 2 3]]

[1 2 3 4 5 6]


In [94]:
X = np.array([[2,9,4],[5,6,1]])
print(X)
print()
print(np.sort(X, axis = 0))
print()
print(np.sort(X, axis = -1))
print()
print(np.sort(X, axis = None))

[[2 9 4]
 [5 6 1]]

[[2 6 1]
 [5 9 4]]

[[2 4 9]
 [1 5 6]]

[1 2 4 5 6 9]


In [97]:
X = np.array([4,10,1,20,45,100,2,1])
print("X = \n", X)
print('sorted =\n', np.sort(X)) #  [  1   1   2   4  10  20  45 100]
print('argsorted =\n', np.argsort(X))
print('partitioned first 3 =\n', np.partition(X, 3)) 
print('argpartitioned first 3 =\n', np.argpartition(X, 3)) 
print('partitioned last 3=\n', np.partition(X, -3)) 
print('argpartitioned last 3=\n', np.argpartition(X, -3))

X = 
 [  4  10   1  20  45 100   2   1]
sorted =
 [  1   1   2   4  10  20  45 100]
argsorted =
 [2 7 6 0 1 3 4 5]
partitioned first 3 =
 [  2   1   1   4  45 100  10  20]
argpartitioned first 3 =
 [6 7 2 0 4 5 1 3]
partitioned last 3=
 [  2   1   1   4  10  20  45 100]
argpartitioned last 3=
 [6 7 2 0 1 3 4 5]


In [99]:
T = np.array([[2,2],[-1,10],[0,1]])
I = np.argsort(np.sum(T,axis=1))
T[I,:]

array([[ 0,  1],
       [ 2,  2],
       [-1, 10]])

In [103]:
u = np.array([100,2,3,4])
v = np.array([1,2,3,4])
w = np.array([4,3,2,1])
print(np.vectorize(max)(u,v,w))
list(map(max, u, v, w))


[100   3   3   4]


[100, 3, 3, 4]

In [105]:
dist = np.vectorize(lambda x, y: np.sqrt(x**2 + y **2))
dist(v,w)

array([4.12310563, 3.60555128, 3.60555128, 4.12310563])

In [108]:
X = np.random.randn(2,3)
print(X)
print(X.T)

y = np.random.randn(3)
print(y)
print(X.dot(y))
print(np.dot(X,y))
print(X.dot(X.T))
print(X.T.dot(X))

[[ 1.34032527 -0.51289807 -1.92645617]
 [ 0.11894089 -0.32905412 -0.43439012]]
[[ 1.34032527  0.11894089]
 [-0.51289807 -0.32905412]
 [-1.92645617 -0.43439012]]
[ 0.89275112  0.87969148 -0.067534  ]
[ 0.87548612 -0.15394539]
[ 0.87548612 -0.15394539]
[[5.77076964 1.16502423]
 [1.16502423 0.31111833]]
[[ 1.81061875 -0.72658824 -2.63374463]
 [-0.72658824  0.37134105  1.13101352]
 [-2.63374463  1.13101352  3.89992817]]


In [110]:
X = np.random.randn(5,3)
print(X)

C = X.T.dot(X)

invC = np.linalg.inv(C)
print(invC)
detC = np.linalg.det(C)
print(detC)
S, U = np.linalg.eig(C)
print(S)
print(U)

[[ 0.12935106 -0.68152951 -0.43355604]
 [-1.0808026   0.41851963  1.02880331]
 [ 1.08946402 -1.08365991 -0.29186843]
 [ 0.09432843  0.69659487 -0.81696699]
 [-0.96440051 -0.32004844 -0.39125155]]
[[ 0.45563553  0.20731085  0.19338916]
 [ 0.20731085  0.54170987 -0.03641985]
 [ 0.19338916 -0.03641985  0.5813392 ]]
10.55759369799414
[4.9057058  1.2882972  1.67050347]
[[ 0.74737949 -0.66070748 -0.06992516]
 [-0.50510943 -0.49667032 -0.70582084]
 [-0.43161136 -0.56283587  0.70493079]]


In [115]:
X = np.array([1,2])
print(np.linalg.norm(X)) # 2-norm, 맨해튼 거리 
print(np.linalg.norm(X, ord=1)) # 1-norm, 유클리드 거리
print(np.linalg.norm(X, ord=np.inf)) # inf-norm, 원소들 중 절대값이 가장 큰 값
print(np.linalg.norm(X, ord=-np.inf)) # -inf-norm, 원소들 중 절대값이 가장 작은 값

2.23606797749979
3.0
2.0
1.0


In [117]:
import math
x = np.array([1,0])
y = np.array([0,1])
print("cosine = ", x.dot(y)/(math.sqrt((x.dot(x)))*math.sqrt((y.dot(y)))))
print("cosine = ", x.dot(y)/(np.linalg.norm(x) * np.linalg.norm(y)))

cosine =  0.0
cosine =  0.0


In [118]:
pts = np.array([1.,2,3,4,5])
u = pts[:, np.newaxis]
v = pts.T[np.newaxis,:]
print(u)
print(v)
np.abs(u-v)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[1. 2. 3. 4. 5.]]


array([[0., 1., 2., 3., 4.],
       [1., 0., 1., 2., 3.],
       [2., 1., 0., 1., 2.],
       [3., 2., 1., 0., 1.],
       [4., 3., 2., 1., 0.]])

In [122]:
pts = np.array([[1,0], [1,1], [0,1]])
print(pts.shape)
u = pts[:,:,np.newaxis]
v = pts.T[np.newaxis,:,:]
print(pts.T.shape)
print(u.shape)
print(v.shape)
print(u)
print(v)

(3, 2)
(2, 3)
(3, 2, 1)
(1, 2, 3)
[[[1]
  [0]]

 [[1]
  [1]]

 [[0]
  [1]]]
[[[1 1 0]
  [0 1 1]]]


In [125]:
print((u-v)**2)

[[[0 0 1]
  [0 1 1]]

 [[0 0 1]
  [1 0 0]]

 [[1 1 0]
  [1 0 0]]]


In [123]:
np.sqrt(np.sum((u-v)**2, axis = 1))

array([[0.        , 1.        , 1.41421356],
       [1.        , 0.        , 1.        ],
       [1.41421356, 1.        , 0.        ]])

In [128]:
np.linalg.norm(u-v, axis=1)

array([[0.        , 1.        , 1.41421356],
       [1.        , 0.        , 1.        ],
       [1.41421356, 1.        , 0.        ]])