In [12]:
import numpy as np

a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a1)
print(a2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 불리언 인덱싱

In [4]:
# 불리언 인덱싱
# True인 인덱스위치만 출력
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[9 4 3 4 4]
[4 3 4]
[9 3 4]


In [7]:
print(a2)
bi = np.random.randint(0, 2, (3, 3), dtype=bool)
print(bi)
print(a2[bi])

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[False False False]
 [False  True False]
 [False  True False]]
[2 8]


# 펜시 인덱싱

In [10]:
# 펜시 인덱싱
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])
ind = np.array([[0, 1,],
               [2, 0]])
print(a1[ind])

[9 4 3 4 4]
[9, 3]
[9 3]
[[9 4]
 [3 9]]


In [14]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row,1])
print(a2[2:,col])
print(a2[row, 1:])
print(a2[1:,col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[[8 9]]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


# 배열 값 삽입
insert()

axis를 지정하지 않으면 1차원 배열로 변환

원본 배열 변경x

In [20]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[ 1  2 10  3  4  5]


In [22]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0) # axis = 0은 행
print(b2)
c2 = np.insert(a2, 1, 10, axis=1) # axis = 1은 열
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


# 배열 값 수정


In [27]:
print(a1)
a1[0] = 3
a1[1] = 2
a1[2] = 1
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4]) # 1, 3, 4번째 인덱스
a1[i] = 0 # 1, 3, 4번째 인덱스의 값이 0 으로 초기화
print(a1)
a1[i] += 4 # 1, 3, 4번째 값에 +4
print(a1)

[9 4 1 4 4]
[3 2 1 4 4]
[9 2 1 4 4]
[9 0 1 0 0]
[9 4 1 4 4]


In [30]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1
print(a2)
a2[1:, 2] = 9
print(a2)
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 9 1]
 [4 2 9]
 [7 8 9]]
[[1 1 1]
 [4 2 9]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


# 배열 값 삭제

delete()사용

axis를 지정하지 않으면 1차원 배열로 변환

삭제할 방향 axis로 지정

원본 배열 변경x

In [32]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 1 4 4]
[9 1 4 4]
[9 4 1 4 4]


In [34]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


# 배열 복사

리스트와 달리 배열의 슬라이스는 복사본이 아님.

copy()는 배열이나 하위 배열 내의 값을 명시적으로 복사

In [36]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)
# a2 원본 배열의 값도 바뀜

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


In [37]:
# copy() 사용
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[0, 0] = 10
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[10  0]
 [ 4  0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]
